### PR TITLE
Added documentation for the spy method andReturns

### PR DESCRIPTION
**Pull request by mkhanal**
andReturns method to a spy was added sometime back but the documentation slipped through the crack.
This PR so addresses the issue #35 

The update fixes issue that were earlier with the previous commit 
Also, the readme has been updated to reflect the requirement for 'pygments' to be installed to generate pages.

### CODE REVIEW

**Comment by lagartoflojo** [comment]
I had to install pygments (`pip install pygments`) in order to correctly generate the pages.
Without it, it tries to access some web service to do the syntax highlighting, and I guess that it's not working correctly.

**Comment by mkhanal** [comment]
Cool...thanks for that...
I'd update the readme as well for it then

**Comment by mkhanal** [comment]
Still running with the issue where the CI fails trying to install mustache.
Funny I don't see mustache gem in the gemfile in the project. Is this a problem with our Travis agents or is there a different settings project that runs the Ci ?

**Comment by mkhanal** [comment]
@slackersoft 
Have you figured out the problems with the build ? Or did you close it because it has been open for some time ?

**Comment by slackersoft** [comment]
Fixed the build issues and pulled in the PR.

**Comment by mkhanal** [comment]
:+1:

**Pull request closed without merging**
