### PR TITLE
Document additional configuration options available when running with NodeJS

### PR DESCRIPTION
**Pull request by coyoteecd**
Documents two config options, one already in 3.5, one pending merge in jasmine-npm repo, see https://github.com/jasmine/jasmine-npm/issues/156

### CODE REVIEW

**Comment by slackersoft** [comment]
Since one of these options is still up for review in the source library, can you please split these options out here so they can be merged/reviewed independently?

Thanks.

**Comment by coyoteecd** [comment]
@slackersoft well I had hoped you'd merge that one first... it's sitting there for some time and it's a small thing to review...

**Comment by coyoteecd** [comment]
@slackersoft got the change merged to master of jasmine-npm repo, so I think you can take the doc change as a single commit now...

**Comment by coyoteecd** [comment]
ping @slackersoft @sgravrock this is more than a year old

**Pull request merged**
