### PR TITLE
Convert custom argument matchers into a markdown tutorial

### PR DESCRIPTION
**Pull request by elliot-nelson**
### SUMMARY

Rewrite the `Custom argument matcher` tutorial as a markdown file.

### DETAILS

- Change title to `Custom argument matchers` (plural).
- Remove side-by-side tutorial and convert it into a regular markdown file.
- Slight text tweaks.
- For code examples, use a concrete (real life) example.

I picked a short tutorial to start with, but if everyone is on board with this look and feel, I'll begin converting the rest of the tutorials as well.

### BEFORE SCREENSHOT

screencapture-jasmine-github-io-tutorials-custom-argument-matcher-2019-05-30-06_59_30

### AFTER SCREENSHOT

screencapture-localhost-4000-tutorials-custom-argument-matchers-2019-05-30-06_59_54

### CODE REVIEW

**Comment by slackersoft** [comment]
I think I would prefer the example of usage to lead with the (presumably) more common case of spy matchers like `toHaveBeenCalledWith` even without the nesting, instead of the `toEqual` case. Or maybe we could do with some prose about how they're the same logic so it works both places?

**Comment by elliot-nelson** [comment]
Totally -- I'm trying to lean towards recognizable real-world examples.

What do you think about:

    spyOn(Buffer, 'alloc').and.callThrough();
    Buffer.alloc(2048);
    expect(Buffer.alloc).toHaveBeenCalledWith(multipleOf(1024));

And then as a follow-up example, showing the nested concept, something like:

    spyOn(request.post);
    expect(request.post).toHaveBeenCalledWith({ name: jasmine.any(String), age: multipleOf(10) });

**Comment by elliot-nelson** [comment]
Updated the example usage code blocks.

New preview: https://elliot-nelson.github.io/jasmine.github.io/tutorials/custom_argument_matchers

**Comment by slackersoft** [comment]
Those look good, I think it does make sense to still have a note about how this all _also_ works inside of `toEqual`. If you have a chance to add that back that would be great. If not, I can get  it in a bit.

**Pull request merged**
